CREATE SCHEMA IF NOT EXISTS neurastate;

CREATE TABLE neurastate.property_point_view (
	x numeric NULL,
	y numeric NULL,
	objectid int4 NOT NULL,
	folio text NULL,
	ttrrss numeric NULL,
	x_coord float8 NULL,
	y_coord float8 NULL,
	true_site_addr text NULL,
	true_site_unit text NULL,
	true_site_city text NULL,
	true_site_zip_code text NULL,
	true_mailing_addr1 text NULL,
	true_mailing_addr2 text NULL,
	true_mailing_addr3 text NULL,
	true_mailing_city text NULL,
	true_mailing_state text NULL,
	true_mailing_zip_code text NULL,
	true_mailing_country text NULL,
	true_owner1 text NULL,
	true_owner2 text NULL,
	true_owner3 text NULL,
	condo_flag text NULL,
	parent_folio text NULL,
	dor_code_cur numeric NULL,
	dor_desc text NULL,
	subdivision text NULL,
	bedroom_count numeric NULL,
	bathroom_count numeric NULL,
	half_bathroom_count numeric NULL,
	floor_count numeric NULL,
	unit_count numeric NULL,
	building_actual_area numeric NULL,
	building_heated_area numeric NULL,
	lot_size numeric NULL,
	year_built int4 NULL,
	assessment_year_cur int4 NULL,
	assessed_val_cur numeric NULL,
	dos_1 date NULL,
	price_1 numeric NULL,
	legal text NULL,
	pid int8 NULL,
	dateofsale_utc timestamptz NULL,
	created_at timestamptz DEFAULT now() NOT NULL,
	updated_at timestamptz DEFAULT now() NOT NULL,
	geom_raw public.geometry(point, 2236) NULL,
	geom public.geometry(point, 4326) NULL,
	CONSTRAINT property_point_view_pkey PRIMARY KEY (objectid)
);

CREATE INDEX idx_property_point_view_geom ON neurastate.property_point_view USING gist (geom);

CREATE TABLE neurastate.property_point_view_staging (
	x numeric NULL,
	y numeric NULL,
	objectid int4 NOT NULL,
	folio text NULL,
	ttrrss numeric NULL,
	x_coord numeric NULL,
	y_coord numeric NULL,
	true_site_addr text NULL,
	true_site_unit text NULL,
	true_site_city text NULL,
	true_site_zip_code text NULL,
	true_mailing_addr1 text NULL,
	true_mailing_addr2 text NULL,
	true_mailing_addr3 text NULL,
	true_mailing_city text NULL,
	true_mailing_state text NULL,
	true_mailing_zip_code text NULL,
	true_mailing_country text NULL,
	true_owner1 text NULL,
	true_owner2 text NULL,
	true_owner3 text NULL,
	condo_flag text NULL,
	parent_folio text NULL,
	dor_code_cur numeric NULL,
	dor_desc text NULL,
	subdivision text NULL,
	bedroom_count numeric NULL,
	bathroom_count numeric NULL,
	half_bathroom_count numeric NULL,
	floor_count numeric NULL,
	unit_count numeric NULL,
	building_actual_area numeric NULL,
	building_heated_area numeric NULL,
	lot_size numeric NULL,
	year_built int4 NULL,
	assessment_year_cur int4 NULL,
	assessed_val_cur numeric NULL,
	dos_1 date NULL,
	price_1 numeric NULL,
	legal text NULL,
	pid int8 NULL,
	dateofsale_utc timestamptz NULL
);

CREATE TABLE neurastate.settings (
    id SERIAL PRIMARY KEY,
    dataset_point_of_view_url TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
